name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: env
      run: |
        export AWS_KEY=${{ secrets.AWS_KEY }}
        export AWS_SECRET=${{ secrets.AWS_SECRET }}
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
